# Convert One-Dimensional Numpy Arrays to Two-Dimensional Row or Column Matrix

A common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. You can do this with the reshape method, or more easily by making use of the newaxis keyword within a slice operation:

In [2]:
import numpy as np

In [9]:
x = np.array([1, 2, 3])

**Row vector via reshape**

In [15]:
x.reshape((1, 3))

array([[1, 2, 3]])

**Row vector via newaxis**

In [16]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [18]:
x[np.newaxis, ...]

array([[1, 2, 3]])

**Column vector via reshape**

In [12]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

**Column vector via newaxis**

In [17]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [19]:
x[..., np.newaxis]

array([[1],
       [2],
       [3]])